train:
  device:
  train_dataset_path:
  validation_dataset_path:
  batch_size: 8
  learning_rate: 0.0001
  number_of_epochs: 10
  model_save_path:
  save_check_point: 1
  model_path:



inference:
  device:
  test_dataset_path:
  model_path: